### ISSUE TITLE
BayesianModel.fit() method gives conditional prob. = 0.5 if conditioned on single variable

### ISSUE THREAD

**Issue by chaconne70** [pgmpy/pgmpy#1005]
### Subject of the issue
After using .fit() method, **conditional probability conditioned on single variable, such as P(Z|X) is always 0.5**
**Conditioned on two variables, such as P(Z|X,Y) gives correct result.**

### Your environment
* pgmpy version 0.1.6
* Python version 3.6.4
* Operating System Windows

### Steps to reproduce
[example-1]
print ('\n Model-1: P(Z|X)')
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator

data = {'X': [0, 0, 0, 0, 1, 1, 1, 1], 'Z': [0, 0, 0, 1, 0, 1, 1, 1]}
data_xz = pd.DataFrame(data)
model_xz = BayesianModel([('X','Z')])
model_xz.fit(data_xz, estimator=MaximumLikelihoodEstimator)
print (model_xz.get_cpds('Z'))

[example-2]
print ('\n Model-2: P(Z|X,Y)')
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator

data = {'X': [0, 0, 0, 0, 1, 1, 1, 1], 'Y': [0, 0, 1, 1, 0, 0, 1, 1], 'Z': [0, 0, 0, 1, 0, 1, 1, 1]}
data_xyz1 = pd.DataFrame(data)
model_xyz1 = BayesianModel([('X','Z'), ('Y','Z')])
model_xyz1.fit(data_xyz1, estimator=MaximumLikelihoodEstimator)
print (model_xyz1.get_cpds('Z'))

### Expected behaviour
[example-1] P(Z|X=0) = 0.25, P(Z|X=1) = 0.75
[example-2] P(Z|X=0, Y=0) = 0, P(Z|X=0, Y=1) = 0.5, P(Z|X=1, Y=0) = 0.5, P(Z|X=1, Y=0) = 1

### Actual behaviour
Conditional probability, conditioned on single variable, is wrong.
[example-1] P(Z|X=0) = 0.5, P(Z|X=1) = 0.5 --> wrong
[example-2] P(Z|X=0, Y=0) = 0, P(Z|X=0, Y=1) = 0.5, P(Z|X=1, Y=0) = 0.5, P(Z|X=1, Y=0) = 1 --> correct !!

**Comment by ankurankan** [comment]
@chaconne70 It seems to be working fine for me:
```
In [1]: from pgmpy.models import BayesianModel
   ...: from pgmpy.estimators import MaximumLikelihoodEstimator
   ...: 
   ...: data = {'X': [0, 0, 0, 0, 1, 1, 1, 1], 'Z': [0, 0, 0, 1, 0, 1, 1, 1]}
   ...: data_xz = pd.DataFrame(data)
   ...: model_xz = BayesianModel([('X','Z')])
   ...: model_xz.fit(data_xz, estimator=MaximumLikelihoodEstimator)
   ...: print (model_xz.get_cpds('Z'))
   ...: 
   ...: [example-2]
   ...: print ('\n Model-2: P(Z|X,Y)')
   ...: from pgmpy.models import BayesianModel
   ...: from pgmpy.estimators import MaximumLikelihoodEstimator
   ...: 
   ...: data = {'X': [0, 0, 0, 0, 1, 1, 1, 1], 'Y': [0, 0, 1, 1, 0, 0, 1, 1], 'Z': [0, 0, 0, 1, 0, 1, 1, 1]}
   ...: data_xyz1 = pd.DataFrame(data)
   ...: model_xyz1 = BayesianModel([('X','Z'), ('Y','Z')])
   ...: model_xyz1.fit(data_xyz1, estimator=MaximumLikelihoodEstimator)
   ...: print (model_xyz1.get_cpds('Z'))
   ...: 
   ...: 
+------+------+------+
| X    | X(0) | X(1) |
+------+------+------+
| Z(0) | 0.75 | 0.25 |
+------+------+------+
| Z(1) | 0.25 | 0.75 |
+------+------+------+
```
Could you share the output of `pip freeze` in your environment ?

**Comment by chaconne70** [comment]
Yes, the result should be like above... but, in my case, it shows different (0.5.)
Seems, something different in environment..
And, 'pip freeze' shows as follows:

click==6.7
Cython==0.27.3
decorator==4.2.1
et-xmlfile==1.0.1
Flask==0.12.2
graphviz==0.8.3.dev0
itsdangerous==0.24
jdcal==1.3
Jinja2==2.10
libpgm==1.3
MarkupSafe==1.0
networkx==1.11
numpy==1.14.1
openpyxl==2.5.1
pandas==0.22.0
pgmpy==0.1.6
pyparsing==2.2.0
pyreadline==2.1
python-dateutil==2.6.1
pytz==2018.3
pywin32==221
scipy==1.0.0
six==1.11.0
Werkzeug==0.14.1
wrapt==1.10.11

**Comment by ankurankan** [comment]
@chaconne70 The error in this case is also because of the higher version of pandas. Downgrading it to `0.19.1` should fix this.

**Comment by chaconne70** [comment]
I changed pandas version to 0.19.2, and now it's working fine. 
There's some problem with higher version of pandas. (but, I don't know from which version it has the problem.. anyway, pandas 0.19.2 works fine for conditional probability estimation.)
Thank you for your help!

**Comment by scottfleming** [comment]
This is still a problem. It has to do with the change in the way that MultIndex behaves between older and newer pandas versions. I've illustrated that [here](https://github.com/scottfleming/pgmpy-examples/blob/master/pandas_versioning_issue_illustration.ipynb). Because the anaconda install of pgmpy automatically downloads pandas 0.23 with pgmpy this is going to be a persistent problem for new users.

**Comment by ankurankan** [comment]
Fixed ref #1050
