### ISSUE TITLE
GibbsSampling sometimes fails because of issue with DiscreteFactor product

### ISSUE THREAD

**Issue by oliver3** [pgmpy/pgmpy#1582]
### Subject of the issue
If I try to run the GibbsSampling for a dataset, it sometimes succeeds, and sometimes fails. This seems to be because `DiscreteFactor` uses `set()` in the `product()` which was introduced in #1548 in July by @ankurankan and the order of `set()` changes for every execution, which causes `phi.variable` to not equal `phi.variables[0]` sometimes.

I think this can be solved by replacing 
```
    new_variables = list(set(phi.variables).union(phi1.variables))
```
by something like
```
    new_variables = phi.variables + [var for var in phi1.variables if var not in phi.variables]
```

### Your environment
* pgmpy version : 0.1.20 and also dev branch (as of november 2022)
* Python version : 3.10.8
* Operating System : MacOS

### Steps to reproduce
The following unit test sometimes succeeds completely, and sometimes fails completely. 

```py
import unittest

from pgmpy.factors import factor_product
from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import BayesianNetwork
from pgmpy.sampling import GibbsSampling


class TestGibbsSamplingIssue(unittest.TestCase):
    def setUp(self):
        self.cpt_cloudy = TabularCPD(variable='Cloudy', variable_card=2, values=[[0.5], [0.5]])
        self.cpt_sprinkler = TabularCPD(variable='Sprinkler', variable_card=2,
                                        values=[[0.5, 0.9], [0.5, 0.1]],
                                        evidence=['Cloudy'], evidence_card=[2])
        self.cpt_rain = TabularCPD(variable='Rain', variable_card=2,
                                   values=[[0.8, 0.2], [0.2, 0.8]],
                                   evidence=['Cloudy'], evidence_card=[2])
        self.cpt_wet_grass = TabularCPD(variable='Wet_Grass', variable_card=2,
                                        values=[[1, 0.1, 0.1, 0.01],
                                                [0, 0.9, 0.9, 0.99]],
                                        evidence=['Sprinkler', 'Rain'],
                                        evidence_card=[2, 2])

        self.dag = BayesianNetwork(
            [('Cloudy', 'Sprinkler'), ('Cloudy', 'Rain'), ('Sprinkler', 'Wet_Grass'), ('Rain', 'Wet_Grass')]
        )
        self.dag.add_cpds(self.cpt_cloudy, self.cpt_sprinkler, self.cpt_rain, self.cpt_wet_grass)

    def test_sampling_gibbs(self):
        # Initial issue
        GibbsSampling(self.dag).sample()

    def test_factor_product(self):
        # Trying to get to the root cause
        factor_product(self.cpt_cloudy, self.cpt_sprinkler, self.cpt_rain)

    def test_product(self):
        self.cpt_cloudy * self.cpt_sprinkler * self.cpt_rain

    def test_mul(self):
        prod = self.cpt_cloudy * self.cpt_sprinkler
        # the order or variables get mixed up, which I believe should not happen
        assert prod.variable == prod.variables[0]

```

### Expected behaviour
It should not throw an error sometimes

### Actual behaviour
```
Traceback (most recent call last):

  File "./pgmpy/pgmpy/factors/discrete/CPD.py", line 299, in copy
    return TabularCPD(
  File "./pgmpy/pgmpy/factors/discrete/CPD.py", line 142, in __init__
    super(TabularCPD, self).__init__(
  File "./pgmpy/pgmpy/factors/discrete/DiscreteFactor.py", line 99, in __init__
    raise ValueError("Variable names cannot be same")
ValueError: Variable names cannot be same
```

**Comment by ankurankan** [comment]
@oliver3 Thanks a lot for reporting this. This seems to be a side-effect of the TabularCPD class inheriting the DiscreteFactor class. I wasn't aware that it is possible to multiply two CPDs to get back another CPD, as I find CPD multiplication to be an ambiguous operation if we don't explicitly specify the variable that we want the final CPD to be defined on. I think the best solution, in this case, is to also define a product method for TabularCPD, which accepts an additional argument to specify the variable on which the final CPD should be defined. What do you think; and please let me know if you would like to create a PR for it? :)

**Comment by oliver3** [comment]
Thanks for looking into it. I am trying to understand what multiplication of CPDs would mean, and how it is used in the Gibbs sampling. 

If I understand correctly the TabularCPD always describes one variable and zero to many evidence variables `Pr(var|x1,x2,x3)`, so I think I can understand something like `Pr(var|x1,x2)Pr(x1) = Pr(var|x2)` (_Edit: oh wait, it should be Pr(var,x1|x2), this can also not be expressed in a TablularCPD then.._) but for instance in the situation above I cannot understand what for the Gibbs sampling would mean `Pr(cloudy)Pr(sprinkler|cloudy)Pr(rain|cloudy)` that would be calculated in https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/sampling/Sampling.py#L428 
For this situation, how would specifying the variable help? Maybe it would suffice in this location to do `to_factor()` first?

**Comment by ankurankan** [comment]
@oliver3 Sorry, I misunderstood the problem initially. And you are correct, converting the CPDs to factor before multiplication at https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/sampling/Sampling.py#L428 should fix the issue in this case.

Now off-topic I guess, I consider CPD multiplication to be essentially 3 steps: 1) Convert both CPDs to factor, 2) Do factor multiplication, and 3) Convert the factor back to CPD. I think the current CPD multiplication is ambiguous because in step 3, we don't know which variable the CPD should be defined on and which variables are the evidence as the factor treats it as a joint. I was suggesting taking the variable on which the final CPD is defined as user input.

**Comment by Alextenz** [comment]
Can any one tell me why I am getting value-error: Variable names cannot be same. It is appearing because the parents node have two child node in which variable is repeated.

**Comment by oliver3** [comment]
I've created a PR but because [networkx just released its 3.0 version](https://networkx.org/documentation/latest/release/release_3.0.html), and the version in the requirements is not fixed, the unit tests start failing because of methods `from_numpy_matrix` and `to_numpy_matrix` not existing anymore. (see https://networkx.org/documentation/latest/release/migration_guide_from_2.x_to_3.0.html#matrix-to-array).

@ankurankan should I fix the version in the `requirements/runtime.txt` to `networkx ~= 2.8.8` in this PR? Or do you have another suggestion?

**Comment by martatubia** [comment]
Did you solve the problems with Gibbs Sampling ValueError: Variable names cannot be same? i don't know how to continue

**Comment by ankurankan** [comment]
@martatubia This should already be fixed in the `dev` branch. If it still doesn't work, could you share your code so that I can reproduce the issue?
