### ISSUE TITLE
writing Bayesian model in a file and read it  later

### ISSUE THREAD

**Issue by faeahi** [pgmpy/pgmpy#949]
### Subject of the issue
I am using pgmpy package for learning Bayesian Network from data and predicting using it.
I want to save learned Bayesian Network in a file and use it for predicting in another time.
I saw your example on pgmpy_notebook but i understood that ProbModelXMLWriter did not work correctly.
Is there another approach for doing this work?

Thanks.

### Your environment
* pgmpy version 0.1.3
* Python version 2.7
* Operating System Windows

**Comment by faeahi** [comment]
I tested this with BifReader but i got this error:
Traceback (most recent call last):

  File "<ipython-input-35-4eda98cedf73>", line 1, in <module>
    runfile('D:/f/tez/py/ff/mankoli/man.py', wdir='D:/f/tez/py/ff/mankoli')

  File "C:\Users\Asus\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Asus\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/f/tez/py/ff/mankoli/man.py", line 1366, in <module>
    fscore,accuracy,precision,recall,traintime,testtime=bic(trainf5_0_1,testf5_0_1,names[namecounter]+str(i),folder,resultlist,address)

  File "D:/f/tez/py/ff/mankoli/man.py", line 267, in bic
    reader=BIFReader('bic.bif')

  File "C:\Users\Asus\Anaconda2\lib\site-packages\pgmpy-0.1.3-py2.7.egg\pgmpy\readwrite\BIF.py", line 60, in __init__
    self.variable_names = self.get_variables()

  File "C:\Users\Asus\Anaconda2\lib\site-packages\pgmpy-0.1.3-py2.7.egg\pgmpy\readwrite\BIF.py", line 147, in get_variables
    name = self.name_expr.searchString(block)[0][0]

  File "C:\Users\Asus\Anaconda2\lib\site-packages\pyparsing.py", line 322, in __getitem__
    return self.__toklist[i]

IndexError: list index out of range
 
Is there any replacement or solution?

**Comment by khalibartan** [comment]
@faeahi Can you share the model and exact procedure that you are using to save the model?

>I am using pgmpy package for learning Bayesian Network from data and predicting using it.
I want to save learned Bayesian Network in a file and use it for predicting in another time.
I saw your example on pgmpy_notebook but i understood that ProbModelXMLWriter did not work correctly.

That notebook hasn't been updated, so there might be some errors (import error for TabularCPD).

**Comment by faeahi** [comment]
@khalibartan Thanks for your reply.
This is my code for creating Bayesian model and writing it:
```
def bic(train,test,name,resultlist,address):
    array=['res']
    trainstart=time()
    
    #structure learning
    bic=BicScore(train)
    hc=HillClimbSearch(train, scoring_method=bic)
    best_model=hc.estimate()
    edges=best_model.edges()
    model=BayesianModel(edges)
    
    #parameter learning
    model.fit(train,estimator=BayesianEstimator, prior_type="BDeu")
    trainend=time()-trainstart

    #check if some nodes are not in the model, delete their corresponding columns from test data
    if (set(model.nodes())-set(array) == set(test.columns)):
        result=model.predict(test).values.ravel()
        pred=list(result)
    else:
        indicator=list(set(test.columns)-set(model.nodes()))
        testchange=test.copy()
        for f in range(len(indicator)):   
            del testchange[indicator[f]]
        teststart=time()
        result=model.predict(testchange).values.ravel()
        testend=time()-teststart
        pred=list(result)

    fscore,accuracy,precision,recall=calscore(resultlist,pred)

    #write the model
    #using ProbModelXML
    model_data = get_probmodel_data(model)
    writer = ProbModelXMLWriter(model_data)
    writer.write_file('probmodelxml.pgmx')
    #using BIF
    #model_data = BIFWriter(model)
    #model_data.write_bif('bic.bif')
    
    #read the model
    #using ProbModelXML
    reader_string = ProbModelXMLReader('probmodelxml.pgmx')
    model2 = reader_string.get_model()
    #using BIF
    #reader=BIFReader('bic.bif')
    #model2=reader.get_model()
       
    return fscore,accuracy,precision,recall,trainend,testend
```

**Comment by khalibartan** [comment]
@faeahi Can you share the data too? It will help us to reproduce the bug. Also, you can try XMLBIF reader and writer class.

**Comment by faeahi** [comment]
I tested  XMLBIF reader and writer class. 
I can predict data with the saved model now but the small issue that exist is that. the saved model predicts the state of data in  the shape of "state0" instead of 0.

this is complete code:
```
def bic(train,test,resultlist):
    array=['res']
    trainstart=time()
    
    #structure learning
    bic=BicScore(train)
    hc=HillClimbSearch(train, scoring_method=bic)
    best_model=hc.estimate()
    edges=best_model.edges()
    model=BayesianModel(edges)
    
    #parameter learning
    model.fit(train,estimator=BayesianEstimator, prior_type="BDeu")
    trainend=time()-trainstart

    #check if some nodes are not in the model, delete their corresponding columns from test data
    if (set(model.nodes())-set(array) == set(test.columns)):
        result=model.predict(test).values.ravel()
        pred=list(result)
    else:
        indicator=list(set(test.columns)-set(model.nodes()))
        testchange=test.copy()
        for f in range(len(indicator)):   
            del testchange[indicator[f]]
        teststart=time()
        result=model.predict(testchange).values.ravel()
        testend=time()-teststart
        pred=list(result)

    fscore,accuracy,precision,recall=calscore(resultlist,pred)

    #write the model
    #using ProbModelXML
    model_data = get_probmodel_data(model)
    writer = ProbModelXMLWriter(model_data)
    writer.write_file('probmodelxml.pgmx')
    #using BIF
    #model_data = BIFWriter(model)
    #model_data.write_bif('bic.bif')
    
    #read the model
    #using ProbModelXML
    reader_string = ProbModelXMLReader('probmodelxml.pgmx')
    model2 = reader_string.get_model()
    #using BIF
    #reader=BIFReader('bic.bif')
    #model2=reader.get_model()
       
    return fscore,accuracy,precision,recall,trainend

trainsxls=pd.ExcelFile("train.xlsx")
traindf=trainsxls.parse("Sheet1")

testsxls=pd.ExcelFile("test.xlsx")
testdf=testsxls.parse("Sheet1")

res=testdf['res']
testdf=testdf.loc[:,:'four']

originalresult=res.as_matrix()
resultlist=list(originalresult)

fscore,accuracy,precision,recall,traintime=bic(traindf,testdf,resultlist)
```
train.xlsx and test.xlsx files are uploader here:
https://www.dropbox.com/s/x7cz3a3pra80fqu/test.xlsx?dl=0
https://www.dropbox.com/s/dtb74bnbsndbfp7/train.xlsx?dl=0

**Comment by zekiblue** [comment]
It there any solution for this question, i am also having the same problem

**Comment by ankurankan** [comment]
@gammazplaude This should be fixed now. There is a caveat though: If the state names for your CPDs are integers (if state names are not explicitly specified, pgmpy will automatically assign integers), when reading back from the file, they are read as strings. Since there is no way to distinguish whether the original state name was an int or str after being written to a file, right now it is always assumed to be str.

**Comment by MathijsPost** [comment]
@ankurankan Hi, I am running into the exact same issue with the `BIFReader`, however for me the issue still arises, I am using pgmpy version 0.1.12 with python 3.7. The `XMLBIFWriter` takes such a long time that I terminate the process after 15 minutes or so with no results. `UAIWriter` also works, but the `UAIReader` doesn't work either for me. Any thought or solutions?

**Comment by MathijsPost** [comment]
@ankurankan I checked, I am able to read a file with strings as states with `BIFReader`. However, I use integers as states, but judging from your last comment I assumed this is not an issue, or is it?

**Comment by ankurankan** [comment]
@MathijsPost I would suggest using BIF as much as possible as it's one of the most tested formats and is quite consistent. You can now actually specify a parameter `state_name_type=int` in the `get_model` method for BIFReader and it will automatically convert the state name to int.

Also, could you tell me more about your network size? Because I just tried XMLBIFWriter on the munin2 network (1k nodes, 1k edges, and 70k parameters) and it works almost instantly for both writing and reading.

**Comment by ankurankan** [comment]
Also if possible could you please open a separate issue for the error that you are getting with UAIReader?

**Comment by MathijsPost** [comment]
@ankurankan Thank you for your quick response. Currently, I have 31 edges for 27 variables, I fit the model on a dataset with 3000 rows of data (ideally I will try to use all 500.000 rows someday). Attached you can find the bif-file, possibly you could give it a try? 

I will open the issue for the UAIReader shortly!

**Comment by ankurankan** [comment]
@MathijsPost I had a quick look at the BIF file that you shared. The error in BIFReader is because of the special characters in the variable names. Right now the reader class expect only alpha numeric, `-`, and `_` characters for the variable names. I will try to fix it.

**Comment by MathijsPost** [comment]
@ankurankan Thank you! That makes sense. Really appreciate your help and the work you are doing!

**Comment by John-Almardeny** [comment]
> BIFReader

Hi @ankurankan 

I could straightforwardly save and load the `BayesianNetwork` model without error using `pickle` in no time because all proposed and available methods in `pumps` take infinite time to finish the process.

Something like:

```
with open(filename, 'wb') as file:
    pickle.dump(model, file, protocol=pickle.HIGHEST_PROTOCOL)

with open(filename, 'rb') as file:
    loaded_model: BayesianNetwork = pickle.load(file)
```

**Comment by ankurankan** [comment]
@John-Almardeny Yes, the reading methods in pgmpy are a bit slow right now due to the dependency on pyparsing (which is quite slow). Pickle should work fine in most cases but might fail when using it between different versions of pgmpy or any dependency package. Also, the file formats are helpful when we want to export/import from any other language.
